name: Auto Sync Fork

on:
  schedule:
    - cron: '0 4 * * *'  # Täglich um 04:00 UTC
  workflow_dispatch:     # Optional: manuell auslösbar

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPO.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge --ff-only upstream/main
          git push origin main
