---
name: Daily Sync from Upstream

"on":
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote
        run: |
          git remote add upstream \
            https://github.com/FirestormViewer/phoenix-firestorm.git || true
          git remote set-url upstream \
            https://github.com/FirestormViewer/phoenix-firestorm.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Sync master branch
        run: |
          git checkout master
          git merge upstream/master --no-edit \
            --allow-unrelated-histories || {
            echo "Merge conflicts detected. Creating a pull request."
            git merge --abort
            exit 1
          }

      - name: Push changes
        run: |
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request on merge conflicts
        if: failure()
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Sync conflicts from upstream - Manual review required'
          body: |
            This pull request contains sync conflicts from the upstream
            repository that require manual resolution.

            Upstream repository:
            https://github.com/FirestormViewer/phoenix-firestorm

            Please review and merge manually.
          branch: sync-conflicts-${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
