name: Release Only

on:
  workflow_dispatch:
    inputs:
      build_version:
        description: 'Build version number'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: firestorm-build
          path: ./release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.event.inputs.build_version }}
          name: "Firestorm Release ${{ github.event.inputs.build_version }}"
          draft: false
          prerelease: false
          files: ./release-files/*
