name: Test Release Only

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: 'Test Setup File'
        required: true
        default: 'Phoenix-FirestormOS-WebRTC_AVX2-7-2-2-79265_Setup.exe'
        type: string

jobs:
  test-release:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Test Setup File
        run: |
          @echo off
          echo Creating test file: %{{ github.event.inputs.test_file }}
          echo. > "%{{ github.event.inputs.test_file }}"
          dir *.exe

      - name: Test GitHub Release
        run: |
          @echo off
          echo Testing release creation...
          echo Setup File: %{{ github.event.inputs.test_file }}
          echo GITHUB_RUN_NUMBER: %GITHUB_RUN_NUMBER%
          echo GITHUB_REPOSITORY: %GITHUB_REPOSITORY%
          
          @REM Test curl command (trockenlauf)
          echo curl -X POST -H "Authorization: token %GITHUB_TOKEN%" https://api.github.com/repos/%GITHUB_REPOSITORY%/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
