name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run build script
        run: |
          # Beispiel: Erzeuge build_data.json
          New-Item -ItemType Directory -Path Firestorm_Build/phoenix-firestorm/build-vc170-64 -Force
          $data = @{ Version = "1.2.3"; Timestamp = (Get-Date).ToString("s") }
          $data | ConvertTo-Json | Set-Content Firestorm_Build/phoenix-firestorm/build-vc170-64/build_data.json

      - name: Save build_data.json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-metadata
          path: Firestorm_Build/phoenix-firestorm/build-vc170-64/build_data.json

  release:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download build_data.json artifact
        uses: actions/download-artifact@v3
        with:
          name: build-metadata

      - name: Extract version from build_data.json
        id: extract_version
        shell: pwsh
        run: |
          $json = Get-Content build_data.json | ConvertFrom-Json
          echo "version=$($json.Version)" >> $env:GITHUB_ENV

      - name: Use version in release step
        run: echo "Releasing version $env:version"
