name: Server Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Installiere Chocolatey (PowerShell)
        shell: powershell
        run: |
          if (-not (Test-Path "$env:ProgramData\\Chocolatey\\bin\\choco.exe")) {
            Write-Host "[INFO] Installiere Chocolatey..."
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
            Start-Sleep -Seconds 30
            & "$env:ProgramData\\Chocolatey\\bin\\refreshEnv.cmd"
          }

      - name: Installiere Tools (CMD)
        shell: cmd
        run: |
          choco install -y --no-progress visualstudio2022community ^
            --package-parameters="--add Microsoft.VisualStudio.Workload.NativeDesktop ^
            --add Microsoft.VisualStudio.Component.VC.14.16.x86.x64 ^
            --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

          choco install -y --no-progress --stop-on-first-failure cmake git python nsis cygwin 7zip doxygen

          if exist "C:\cygwin64\cygwinsetup.exe" (
              C:\cygwin64\cygwinsetup.exe -q -P patch
          ) else (
              echo [WARN] Cygwin Setup nicht gefunden unter C:\cygwin64\cygwinsetup.exe
          )
