name: Windows Server 2025 Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Bereinige Build-Verzeichnisse (CMD)
        shell: cmd
        run: |
          rmdir /S /Q C:\Firestorm_Build
          rmdir /S /Q C:\temp
          del /F /Q %TEMP%\* >nul 2>&1

      - name: Bereinige temporäre Dateien (PowerShell)
        shell: powershell
        run: |
          Remove-Item -Recurse -Force "C:\Firestorm_Build" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force "$env:TEMP\*" -ErrorAction SilentlyContinue

      - name: Installiere Chocolatey (PowerShell)
        shell: powershell
        run: |
          if (-not (Test-Path "$env:ProgramData\\Chocolatey\\bin\\choco.exe")) {
            Write-Host "[INFO] Installiere Chocolatey..."
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
            iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
            Start-Sleep -Seconds 30
            & "$env:ProgramData\\Chocolatey\\bin\\refreshEnv.cmd"
          }

      - name: Installiere Visual Studio 2022 Build Tools
        shell: powershell
        run: |
          choco install -y --no-progress visualstudio2022buildtools --package-parameters="--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive"

      - name: Installiere zusätzliche Tools
        shell: powershell
        run: |
          choco install -y --no-progress cmake git python nsis cygwin 7zip ninja

      - name: Installiere Cygwin-Paket „patch“
        shell: powershell
        run: |
          $cygwinSetup = "C:\tools\cygwin\setup-x86_64.exe"
          if (Test-Path $cygwinSetup) {
            & $cygwinSetup -q -P patch
          }
